#ifndef MGBDEBUG_H
#define MGBDEBUG_H
#include <QDebug>

//WARNING -> DO NOT RENAME THIS MACROS , YOU WILL DESTROY THE SOURCE CODE
#define PRINT_ACTION_TRIGGERED_MESSAGES 1
#define PRINT_ERROR_MESSAGES 0
#define PRINT_ALERT_MESSAGES 0
#define PRINT_MAGABE_DB_AND_MODEL_MESSAGES 0
#define PRINT_DATA_SENT 0
#define PRINT_DATA_RECEIVED 0
#define PRINT_MESAE_DEBUG_MESSAGES 0
#define PRINT_User_Class_DEBUG_MESSAGES 0
#define PRINT_MSignalsManagerClass_DEBUG_MESSAGES 0
#define MAGABE_SERVER_PRINT_AUTHENTICATION_STATUS_IN_ControllerClass_performActionMethod 0
#define PRINT_MOpaque_Class_DEBUG_MESSAGES 0

#endif // MGBDEBUG_H
